name: sudapy
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - geopandas>=0.14
  - shapely>=2.0
  - fiona>=1.9
  - pyproj>=3.6
  - rasterio>=1.3
  - pandas>=2.0
  - numpy>=1.24
  - scipy>=1.10
  - matplotlib>=3.7
  - folium>=0.15
  - contextily>=1.4
  - gdal>=3.6
  - pip
  - pip:
      - sudapy
